include:
  - board: seeeduino_xiao_ble
    shield: sessile_central
    snippet: studio-rpc-usb-uart
    artifact-name: sessile_central
    
  - board: seeeduino_xiao_ble
    shield: sessile_peripheral
    artifact-name: sessile_peripheral

  - board: nice_nano_v2
    shield: sessile_dongle
    snippet: studio-rpc-usb-uart
    artifact-name: sessile_dongle

  - board: seeeduino_xiao_ble
    shield: settings_reset
    artifact-name: settings_reset_xiao

  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: settings_reset_nnv2
