name: Build RMK firmware
on:
  workflow_dispatch:
  push:
    paths:
      - "rmk/**"
      - ".github/workflows/rmk.yml"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: cargo-bins/cargo-binstall@main
      - uses: actions/checkout@v4
      - name: Cache cargo registry and build
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            rmk/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('rmk/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: Install flip-link and cargo-make
        run: cargo binstall cargo-make flip-link -y
      - name: Install Rust toolchain
        run: rustup target add thumbv7em-none-eabihf
      - name: Build uf2 firmware
        working-directory: ./rmk
        run: cargo make uf2 --release
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: rmk/*.uf2

  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    needs: build
    steps:
      - uses: actions/download-artifact@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: rmk/*.uf2