// footprint file for ergogen automatically generated by kicad-to-ergogen
// include it in ergogen/src/footprints/index.js using
//     require('path/to/this/file.js')
module.exports = {
  params: {
    designator: 'BAT',
    VBAT: { type: 'net', value: 'VBAT' },
    GND: { type: 'net', value: 'GND' }
  },
  body: p => {
    return `(module
      easyeda2kicad:CONN-TH_MY-LR44-03-J
      (layer F.Cu)
      ${p.at /* parametric position */}
      (attr through_hole)
      (fp_text reference "${p.ref}" (at 0 -4.45 ${p.rot}) (layer F.SilkS) (effects (font (size 1 1) (thickness 0.15))) ${p.ref_hide})
      (fp_text value CONN-TH_MY-LR44-03-J (at 0 4.44 ${p.rot}) (layer F.Fab) (effects (font (size 1 1) (thickness 0.15))))
      (fp_text user %R (at 0 0 ${p.rot}) (layer F.Fab) (effects (font (size 1 1) (thickness 0.15)))) 
      (property "LCSC" "C5457116" (at 0 0 0) (effects (font (size 1.27 1.27) ) (hide yes)))
      (fp_line (start 6.60 -5.59) (end 6.60 -1.98) (layer F.SilkS) (width 0.25))
      (fp_line (start -6.61 -5.59) (end -6.61 -1.98) (layer F.SilkS) (width 0.25))
      (fp_line (start 3.56 6.46) (end 6.60 3.42) (layer F.SilkS) (width 0.25))
      (fp_line (start -3.58 6.39) (end -6.61 3.36) (layer F.SilkS) (width 0.25))
      (fp_line (start -6.61 -5.59) (end 6.60 -5.59) (layer F.SilkS) (width 0.25))
      (pad 2 smd circle (at 0 0.44 ${p.rot}) (size 8.00 8.00) (layers F.Cu F.Paste F.Mask) ${p.GND.str})
      (pad 1 thru_hole circle (at -6.61 -0.45 ${p.rot}) (size 2.60 2.60) (layers *.Cu *.Mask) (drill 2) ${p.VBAT.str})
      (pad 1 thru_hole circle (at 6.61 -0.45 ${p.rot}) (size 2.60 2.60) (layers *.Cu *.Mask) (drill 2) ${p.VBAT.str})
      (model "board/sessile.3dshapes/CONN-TH_MY-LR44-03-J.wrl" (offset (xyz 0.000 -0.440 6)) (scale (xyz 1 1 1)) (rotate (xyz 0 0 0)))
    )`
  }
}