// footprint file for ergogen automatically generated by kicad-to-ergogen
// include it in ergogen/src/footprints/index.js using
//     require('path/to/this/file.js')
module.exports = {
  params: {
    designator: 'D',
    pad1: { type: 'net', value: 'pad1' },
    pad2: { type: 'net', value: 'pad2' },
    pad3: { type: 'net', value: 'pad3' },
    pad4: { type: 'net', value: 'pad4' },
    pad5: { type: 'net', value: 'pad5' },
  },
  body: p => {
    return `(module
      easyeda2kicad:SOT-353_L2.1-W1.3-P0.65-LS2.3-BL
      (layer F.Cu)
      (tedit 5DC5F6A4)
      ${p.at /* parametric position */}
      (attr smd)
      (fp_text reference "${p.ref}" (at 0 -2.5 ${p.rot}) (layer F.SilkS) (effects (font (size 1 1) (thickness 0.15))) ${p.ref_hide})
      (fp_text value UMP1NTR (at 0 5.15 ${p.rot}) (layer F.Fab) (effects (font (size 1 1) (thickness 0.15))) ${p.ref_hide})
      (fp_text user %R (at 0 0 ${p.rot}) (layer F.Fab) (effects (font (size 1 1) (thickness 0.15))))
      (property Footprint SOT-353_L2.1-W1.3-P0.65-LS2.3-BL (at 0 0 0) (effects (font (size 1 1) (thickness 0.15)) (hide yes)))
      (property "LCSC" "C510065" (at 0 0 0) (effects (font (size 1.27 1.27) ) (hide yes)))
      (fp_line (start 1.14 0.51) (end 1.14 -0.51) (layer F.SilkS) (width 0.25))
      (fp_line (start -1.14 -0.51) (end -1.14 0.51) (layer F.SilkS) (width 0.25))
      (pad 1 smd rect (at -0.65 1.15 ${p.rot}) (size 0.40 0.80) (layers F.Cu F.Paste F.Mask) ${p.pad1.str})
      (pad 2 smd rect (at 0 1.15 ${p.rot}) (size 0.40 0.80) (layers F.Cu F.Paste F.Mask) ${p.pad2.str})
      (pad 3 smd rect (at 0.65 1.15 ${p.rot}) (size 0.40 0.80) (layers F.Cu F.Paste F.Mask) ${p.pad3.str})
      (pad 4 smd rect (at 0.65 -1.15 ${p.rot}) (size 0.40 0.80) (layers F.Cu F.Paste F.Mask) ${p.pad4.str})
      (pad 5 smd rect (at -0.65 -1.15 ${p.rot}) (size 0.40 0.80) (layers F.Cu F.Paste F.Mask) ${p.pad5.str})
      (fp_circle (center -1.02 1.15) (end -0.99 1.15) (layer F.Fab) (width 0.06))
      (fp_circle (center -0.70 1.46) (end -0.60 1.46) (layer Cmts.User) (width 0.20))
      (model "board/sessile.3dshapes/SOT-353-5P_L2.0-W1.3-H1.1-LS2.0-P0.65.wrl" (offset (xyz 0.000 -0.000 -0.000)) (scale (xyz 1 1 1)) (rotate (xyz 0 0 270)))
    )`
  }
}